#!/bin/bash -exu
SCRIPT_HOME="$(cd "$(dirname "$0")"; pwd)"
COMPONENT_HOME="$(cd "${SCRIPT_HOME}/../.."; pwd)"

cd "${COMPONENT_HOME}"

tmp_dir=$(mktemp -d -t dnd-sbt-XXXXXXXXXX)
cp -R . ${tmp_dir}

docker run \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /usr/bin/docker:/usr/bin/docker \
  -v ${HOME}/.docker/config.json:/root/.docker/config.json \
  -v ${tmp_dir}:/root/ \
  -e GITHUB_TOKEN=${GITHUB_TOKEN} \
  sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.2_13_1.9.9_2.12.19 \
  /bin/bash -c "git config --global --add safe.directory /root; sbt ${1}"
