name: Security Scan
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  security-scan:
    name: Security Scan
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: raw-labs/das-sec-scan@v0.2.0
        with:
          github-token: ${{ github.token }}
